services:
  - type: web
    name: vidgetnow-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t vidgetnow-backend .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 300 app:app
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
